
# File:  .github/workflows/workflow.yml

on: [push]

name: AzurePowerShellLoginSample

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: Check out code
      uses: actions/checkout@v2
        
    - name: Login to acr
      uses: azure/docker-login@v1
      with:
        login-server: contosocontainerregistry2691.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t contosocontainerregistry2691.azurecr.io/clumsybird:${{ github.sha }}
        docker push contosocontainerregistry2691.azurecr.io/clumsybird:${{ github.sha }}
    - name: setup kubectl
      uses: azure/setup-kubectl@v1
    - run: |
        kubectl run clumsy-bird --image contosocontainerregistry2691.azurecr.io/clumsybird:${{ github.sha }} -o yaml --dry-run|kubectl apply -n aksgithubcluster -f -
        kubectl -n aksgithubcluster expose deploy clumsy-bird --port 80 --type LoadBalancer -o yaml --dry-run|kubectl apply -n dev -f -
        
