
# File:  .github/workflows/workflow.yml

on: [push]

name: AzurePowerShellLoginSample

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Login via Az module
      uses: azure/login@v1
      with:
        login-server: contosocontainerregistry2691.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t contosocontainerregistry2691.azurecr.io/clumsybird:${{ github.sha }}
        docker push contosocontainerregistry2691.azurecr.io/clumsybird:${{ github.sha }}
        
