name: CI 
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkouts@v2
    - uses: Azure/docker-login@v1
      with:
        login-server: aksgithub.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t aksgithub.azurecr.io/clumsy-bird:${{ github.sha}}
        docker push aksgithub.azurecr.io/clumsy-bird:${{ github.sha}}
